# Scan this file for changes every 30 seconds
refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{l} [{h({t})}]: {m}{n}"

  logfile:
    kind: file
    path: "log/ton-node.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S.%f)} {l} [{h({t})}]: {m}{n}"

  tvm_logfile:
    kind: file
    path: "log/tvm.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S.%f)} {l} [{h({t})}]: {m}{n}"

root:
  level: debug
  appenders:
    - logfile

loggers:
  # TON Node messages
  node:
    level: debug
    appenders:
      - stdout

  # ADNL messages
  adnl:
    level: off

  executor:
    level: error

  # TVM messages. Switching level to `trace` will give you a lot of information about contracts execution,
  # but can significantly slow down the node and increase disk usage.
  tvm:
    level: error
    appenders:
      - tvm_logfile

  ## Next targets for PoA:
  poa:
    level: off

  engine:
    level: error
    appenders:
      - stdout

  network:
    level: off

  shutdown:
    level: warn
    appenders:
      - stdout
